---
title: "Hello, GPT project!"
author: "<REPLACE THIS WITH YOUR NAME>"
format: html
editor: visual
bibliography: references.bib
execute:
  echo: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(tidyquant)
library(tsfe)
library(fpp2)
library(gt)
```

## Introduction

-   Set the statement in the context of modern financial research practices

-   Use high-quality research to illustrate the pros and cons of the statement. (for example the above 2 papers)

-   Choose a classic research problem in finance. For example

-   Is there a publication bias crisis in finance research?

-   Is climate finance a fad or the future?

-    Is finance research becoming less impactful for the financial services industry?

::: callout-tip
It should be sufficiently non-technical that an intelligent person who is unfamiliar with the field could grasp what the study is about. The introduction should include a summary of the relevant articles in the field. At a minimum, the papers provided should be summarized in the student's own words. The end of the introduction should introduce what is going to happen in the rest of the paper.

Use high-quality literature to illustrate the pros and cons of the argument.

Some examples of how to use the `.bib` to add references

-   In line, @dowling2023 will render as Dowling and Lucey (2023)

-   And [@hutson2022] renders as (Hutson, 2022)

If this is too complicated, you can manually copy and paste referencing.

**Tip:** A good introduction should provide answers to the "What are the aims and objective of the research?", "Does it address a new problem or an old problem in a new way?" A good literature review critically assesses the research to date.
:::

## Data and methods

::: callout-tip

-   a brief explanation of the GPT model you used

-   The raw financial research questions you used as input data (should
    be based on classical financial research questions that you studied in
    the first semester)

-   Prompt engineering techniques you used
:::

## Results

::: callout-tip
Detail the generative results from your GPT models and critique your output. 
:::

## Conclusion

::: callout-tip
Summarise and state your critical assessment of the statement using the
scientific evidence presented in the previous sections. Students should
use a quarto report to produce a HTML file for submission. 

- ** Submit both a HTML report and the quarto document using a zip file to Canvas**
- **The lecturer reserves the right to examine students orally after each assessment if he suspects *foul play.**

:::

# Appendix

I'm sharing a summary of all the prompt engineering you have done here.

# References

*This is where the cited references should appear when you render the document to a HTML*
